Fix eager load
Just file name like 'require "users_controller"' fails.
Besides, 'require "app/controllers/users_controller"' is also ambiguous.
So make it loads with full path

```
E

Error:
RoutingTest#test_that_application_has_correct_routes:
LoadError: No such file to load -- application_controller.rb
    test/routing/routing_test.rb:6:in `test_that_application_has_correct_routes'

rails test test/routing/routing_test.rb:4

Finished in 480.253456s, 0.0021 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```